basePath: /
definitions:
  model.ChannelResponse:
    properties:
      code:
        type: string
      createdAt:
        type: string
      fixedFee:
        type: number
      iconUrl:
        type: string
      id:
        type: integer
      libName:
        type: string
      mdr:
        type: string
      name:
        type: string
      orderNum:
        type: integer
      paymentMethod:
        $ref: '#/definitions/model.PaymentMethod'
      updatedAt:
        type: string
    type: object
  model.ChannelResponseWrapper:
    properties:
      data:
        $ref: '#/definitions/model.ChannelResponse'
      error:
        type: string
      meta:
        $ref: '#/definitions/model.PaginationPage'
      success:
        type: boolean
    type: object
  model.ChannelsResponseWrapper:
    properties:
      data:
        items:
          $ref: '#/definitions/model.ChannelResponse'
        type: array
      error:
        type: string
      meta:
        $ref: '#/definitions/model.PaginationPage'
      success:
        type: boolean
    type: object
  model.CreateChannelRequest:
    properties:
      code:
        type: string
      fixedFee:
        type: number
      iconUrl:
        type: string
      libName:
        type: string
      mdr:
        type: integer
      name:
        type: string
      orderNum:
        type: integer
      paymentMethodId:
        type: integer
      userAction:
        type: string
    required:
    - code
    - name
    - paymentMethodId
    - userAction
    type: object
  model.CreateMethodRequest:
    properties:
      code:
        type: string
      desc:
        type: string
      name:
        type: string
      orderNum:
        type: integer
      userAction:
        type: string
    required:
    - code
    - name
    - userAction
    type: object
  model.ErrorWrapper:
    properties:
      data: {}
      error:
        type: string
      meta:
        $ref: '#/definitions/model.PaginationPage'
      success:
        type: boolean
    type: object
  model.MethodResponse:
    properties:
      code:
        type: string
      createdAt:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      orderNum:
        type: integer
      updatedAt:
        type: string
      userAction:
        type: string
    required:
    - code
    - name
    - userAction
    type: object
  model.MethodResponseWrapper:
    properties:
      data:
        $ref: '#/definitions/model.MethodResponse'
      error:
        type: string
      meta:
        $ref: '#/definitions/model.PaginationPage'
      success:
        type: boolean
    type: object
  model.MethodsResponseWrapper:
    properties:
      data:
        items:
          $ref: '#/definitions/model.MethodResponse'
        type: array
      error:
        type: string
      meta:
        $ref: '#/definitions/model.PaginationPage'
      success:
        type: boolean
    type: object
  model.PaginationPage:
    properties:
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  model.PaymentMethod:
    properties:
      code:
        type: string
      id:
        type: integer
    type: object
  model.UpdateChannelRequest:
    properties:
      code:
        type: string
      fixedFee:
        type: number
      iconUrl:
        type: string
      libName:
        type: string
      mdr:
        type: integer
      name:
        type: string
      orderNum:
        type: integer
      paymentMethodId:
        type: integer
      userAction:
        type: string
    required:
    - code
    - name
    - paymentMethodId
    - userAction
    type: object
  model.UpdateMethodRequest:
    properties:
      code:
        type: string
      desc:
        type: string
      name:
        type: string
      orderNum:
        type: integer
      userAction:
        type: string
    required:
    - code
    - name
    - userAction
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a sample swagger for Fiber
  title: SVD Clone API
  version: "1.0"
paths:
  /api/channels:
    get:
      consumes:
      - application/json
      description: Find a payment channel by its ID.
      parameters:
      - description: Filter by channel name
        in: query
        name: name
        type: string
      - description: Filter by channel code
        in: query
        name: code
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChannelsResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Find a payment channels
      tags:
      - Channels
    post:
      consumes:
      - application/json
      description: Create a new payment channel with the provided details.
      parameters:
      - description: Create Channel Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateChannelRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChannelResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Create a new payment channel
      tags:
      - Channels
  /api/channels/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a payment channel with the provided details.
      parameters:
      - description: Channel ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChannelResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Delete a payment channel
      tags:
      - Channels
    get:
      consumes:
      - application/json
      description: Find a payment channel by its ID.
      parameters:
      - description: Channel ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChannelResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Find a payment channel by ID
      tags:
      - Channels
    put:
      consumes:
      - application/json
      description: Update a payment channel with the provided details.
      parameters:
      - description: Update Channel Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateChannelRequest'
      - description: Channel ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ChannelResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Update a payment channel
      tags:
      - Channels
  /api/methods:
    get:
      consumes:
      - application/json
      description: Find a payment methods by its ID.
      parameters:
      - description: Filter by method name
        in: query
        name: name
        type: string
      - description: Filter by method code
        in: query
        name: code
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MethodsResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Find a payment methods
      tags:
      - Methods
    post:
      consumes:
      - application/json
      description: Create a new payment method with the provided details.
      parameters:
      - description: Create Method Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateMethodRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MethodResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Create a new payment method
      tags:
      - Methods
  /api/methods/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a payment method with the provided details.
      parameters:
      - description: Method ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MethodResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Delete a payment method
      tags:
      - Methods
    get:
      consumes:
      - application/json
      description: Find a payment method by its ID.
      parameters:
      - description: Method ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MethodResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Find a payment method by ID
      tags:
      - Methods
    put:
      consumes:
      - application/json
      description: Update a payment method with the provided details.
      parameters:
      - description: Update Method Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateMethodRequest'
      - description: Method ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MethodResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorWrapper'
      summary: Update a payment method
      tags:
      - Methods
swagger: "2.0"
